koco/src/components/layout/PageHeader/index.tsx, koco/src/pages/ProblemListPage/components/Calendar/index.tsx, koco/src/pages/ProblemListPage/components/ProblemItem/index.tsx, koco/src/pages/ProblemListPage/index.tsx, koco/src/pages/SurveyPage/index.tsx, koco/src/routes/RootRoutes.tsx
[FEATURE] 문제 리스트 조회 페이지 개발 (#8)
날짜에 따라 문제 리스트를 조회할 수 있는 페이지를 개발합니다.
- #8 
다른 페이지에서 재사용하기 위해 뒤로가기 버튼과 타이틀이 있는 헤더를 공통 컴포넌트로 분리하였습니다.
=> [FEATURE] 문제 리스트 조회 페이지 개발 (#8)

koco/package-lock.json, koco/package.json, koco/src/pages/MainPage/components/ContinuousCard/index.tsx, koco/src/pages/MainPage/components/ProfileCard/index.tsx, koco/src/pages/MainPage/components/TotalStudyCard/components/RadarChart/index.tsx, koco/src/pages/MainPage/components/TotalStudyCard/index.tsx, koco/src/pages/MainPage/index.tsx, koco/src/pages/ProblemListPage/index.tsx, koco/src/temp/mock/dashboard.json
[FEATURE] 메인 페이지 - 레이더 차트 개발
chart.js, react-chartjs-2 사용하여 레이더 차트를 구현하였습니다.
- close #14 
사용자 메인페이지에서 mock data를 기반으로 데이터를 연결하였습니다.
- chart.js, react-chartjs-2 는 추후 도넛, 막대 그래프 등 다른 통계 페이지를 구현하기 위해서 사용할 예정입니다.
=> [FEATURE] 메인 페이지 - 레이더 차트 개발 (#14)

koco/src/apis/authApi.ts, koco/src/apis/axios/index.ts, koco/src/apis/problemApi.ts, koco/src/apis/userApi.ts, koco/src/components/layout/BottomNav/index.tsx, koco/src/hooks/mutations/useAuthMutations.ts, koco/src/hooks/mutations/useProblemMutations.ts, koco/src/hooks/mutations/useUserMutations.ts, koco/src/hooks/queries/useProblemQueries.ts, koco/src/pages/FirstLoginPage/index.tsx, koco/src/pages/KakaoCallbackPage/index.tsx, koco/src/pages/ProblemListPage/components/ProblemItem/index.tsx, koco/src/pages/ProblemListPage/index.tsx, koco/src/pages/ProblemSolutionPage/components/ProblemDetailSection/index.tsx, koco/src/pages/ProblemSolutionPage/components/ProblemSolutionSection/index.tsx, koco/src/pages/ProblemSolutionPage/index.tsx, koco/src/pages/SurveyPage/index.tsx, koco/src/provider/QueryProvider/index.tsx, koco/src/temp/mock/dashboard.ts
[CHORE] API 연결 수정 (#21)
백엔드 로컬 서버를 기반으로 api 연결을 테스트 하였으며 일부 라우팅 로직을 수정하였습니다.
- close #21 
- bottom navigation의 코드 해설집 바로가기 라우팅 수정
- 기타 api 연결 및 더미데이터 제거, 타입 수정
- 백엔드 개발 상황에 따라 메인페이지 api 연결 및 테스트 필요 (미완료)
- 라우팅 경로 제한(문제 해설 페이지)하는 로직 구현 필요
=> [CHORE] API 연결 수정 (#21)

koco/src/routes/RootRoutes.tsx, koco/tsconfig.json, koco/vite.config.ts
[CHORE] QA 모드 설정 (#34)
QA 모드일 시 /admin/preview 경로로 이동하도록 설정
- closes #34
- vite.config.ts 설정을 수정하였으며, BrowserRouter의 basename을 수정하였습니다.
=> [CHORE] QA 모드 설정 (#34)

koco/src/pages/SurveyPage/index.tsx
[BUG] 문제 데이터가 없을 시에도 설문 제출이 가능한 현상 수정 (#38)
문제 데이터가 없을 경우 설문 페이지의 '오늘의 문제가 없습니다'가 띄워지도록 구현
- close #38 
- 문제 데이터가 없을 경우 '오늘의 문제 데이터가 없습니다' 문구가 띄워지도록 수정, 설문 등록 버튼이 보이지 않도록 수정
=> [BUG] 문제 데이터가 없을 시에도 설문 제출이 가능한 현상 수정 (#38)

koco/src/pages/ProblemListPage/components/ProblemItem/index.tsx, koco/src/pages/ProblemListPage/index.tsx, koco/tailwind.config.ts
[CHORE] 문제 리스트 조회 페이지 - 티어 라벨링 관련 디자인 시스템 설정 (#26)
tier 값에 따라 라벨의 색이 다르게 보이도록 구현합니다.
- closes #26 
- tier값이 title 대신 중복으로 들어가 있었던 에러를 수정하였습니다.
- tier 값을 파싱해,tailwind.config.ts에 기재된 디자인 시스템 tier 색상에 매핑하였습니다.
-  tier 값이 어떻게 오는지 확인 필요
=> [CHORE] 문제 리스트 조회 페이지 - 티어 라벨링 관련 디자인 시스템 설정 및 적용(#26)

koco/src/components/layout/Header/index.tsx
[BUG] logo click event 제거 (#42)
로고를 클릭 했을 때 이전 작업으로 이동하는 이벤트가 적용되어 있던 것을 제거합니다.
- closes #42 
- 로고 클릭 시 navigate(-1)이 실행되었지만, 로고를 클릭했을 때 실행할 이벤트는 없어야 하므로 제거하였습니다.
=> [BUG] logo click event 제거 (#42)

koco/src/@types/problem/index.ts, koco/src/pages/MainPage/components/ProfileCard/index.tsx, koco/src/pages/ProblemListPage/components/ProblemItem/index.tsx, koco/src/pages/ProblemListPage/index.tsx, koco/src/pages/SurveyPage/index.tsx
[FEATURE] 오늘의 설문 한 번만 수행할 수 있도록 수정 (#41)
설문 관련한 버그를 수정하고, 오늘의 설문을 한 번만 수행할 수 있도록 수정하였습니다.
closes #41 #45 
navigate 시 state로 date를 보내게 하여, 문제 리스트 조회 시 설문이 완료 되지 않은 경우 해당 날짜의 설문으로 정상적으로 이동할 수 있도록 수정하였습니다.
오늘의 설문은 isAnswered에 따라 한 번만 수행할 수 있도록 로직을 수정하였습니다.
=> [FEATURE] 오늘의 설문 한 번만 수행할 수 있도록 수정 (#41, #45)

koco/src/pages/ProblemListPage/components/ProblemItem/index.tsx, koco/src/pages/ProblemSolutionPage/components/ProblemDetailSection/index.tsx, koco/src/utils/converter/convertTier.ts
[FEATURE] 백준 티어 랭킹 데이터 문자열로 매핑 (#50)
기존의 백준 티어 데이터가 '6.0'으로 오던 것을 'Silver 5'와 같은 형태로 변환하도록 유틸 함수를 구현하였습니다.
- closes #50 
- 티어 데이터가 숫자로 표시되는 이슈가 있어 수정하였습니다.
- 문제 해설 페이지의 데이터 출력 부분에 whitespace-pre-line 클래스를 적용하지 않은 것을 발견하여 수정하였습니다.
=> [FEATURE] 백준 티어 랭킹 데이터 문자열로 매핑 (#50)

koco/src/pages/SurveyPage/index.tsx
[CHORE] 데이터가 비어 있을 경우 핸들링 (#58)
오늘의 설문 데이터가 비어 있을 경우 보여줄 UI 구현
closes #58 
- react-query의 error 변수를 사용하여 403 코드일 경우 '오늘의 문제가 없습니다' 렌더링하도록 구현하였습니다.
=> [CHORE] 설문 페이지 - 데이터가 비어 있을 경우 핸들링 (#58)

koco/src/pages/ProblemListPage/index.tsx, koco/src/pages/SurveyPage/index.tsx
[BUG] 문제 리스트 조회 페이지 - 날짜 선택 시 쿼리 파라미터 변동 및 refetch 하도록 로직 수정 (#57)
설문 등록 후 다시 해당 문제로 돌아왔을 때 현재 날짜로 선택되어 있는 버그를 수정하였습니다.
- closes #57 
- 설문 등록 후 /problems 페이지로 이동하는 라우팅을 /problems?date=2025-05-12 와 같이 쿼리 파라미터로 date를 넘기는 로직으로 수정하였습니다.
- 문제 리스트 조회 페이지에서 date를 선택할 때마다 query parameter가 변동되어, refetch하도록 수정하였습니다.
- 최적화가 필요할 것으로 예상됩니다.
=> [BUG] 문제 리스트 조회 페이지 - 날짜 선택 시 쿼리 파라미터 변동 및 refetch 하도록 로직 수정 (#57)

koco/src/@types/user/index.ts, koco/src/apis/axios/index.ts, koco/src/apis/userApi.ts, koco/src/hooks/queries/queryKeys.ts, koco/src/hooks/queries/useUserQueries.ts, koco/src/pages/MainPage/components/ProfileCard/index.tsx, koco/src/pages/MainPage/index.tsx, koco/src/pages/SurveyPage/index.tsx
[FEATURE] 메인 페이지 - 유저 프로필 조회, 알고리즘 스탯 조회 API 연결 (#69)
기존의 대시보드 API에서 분리된 유저 프로필 조회, 알고리즘 스탯 조회 API를 연결합니다.
closes #69 
- API 호출을 위한 useQuery custom 훅 생성 (useUserProfile, useUserStats)
=> [FEATURE] 메인 페이지 - 유저 프로필 조회, 알고리즘 스탯 조회 API 연결 (#69)

koco/src/pages/ProblemSolutionPage/components/ProblemSolutionSection/index.tsx
[BUG] 문제 요약 부분 줄바꿈이 이상한 문제 (#86)
문제 해설 페이지의 문제 요약 부분(problemSolving)의 파싱이 적절하지 못한 부분을 수정하였습니다.
- closes #86
- '숫자.' 형태를 정규 표현식으로 검사해 줄바꿈을 하던 기존 로직을 '다.'를 검사하여 줄바꿈하는 것으로 수정하였습니다.
=> [BUG] 문제 요약 부분 줄바꿈이 이상한 문제 (#86)

koco/package-lock.json, koco/package.json, koco/src/main.tsx, koco/src/pages/ProblemSolutionPage/components/ProblemDetailSection/index.tsx, koco/src/styles/global.css, koco/src/utils/converter/processMathText.ts, koco/src/vite-env.d.ts
- 수식 렌더링을 위한 데이터 전처리 함수 `processMathText` 구현
- `better-react-mathjax`를 사용해 수식 렌더링 처리
closes #81 
DB 상의 데이터에 텍스트와 수식 데이터가 중복으로 포함되어 저장되었습니다. (예: N-1$N-1$ -> $N-1$ 이 되어야 함)
따라서 `$...$` 수식 표현을 기준으로, 앞에 붙은 중복 텍스트를 제거하는 `processMathText` 함수를 구현하였습니다.
잘못된 데이터를 클린하게 정제한 후 `better-react-mathjax`를 통해 수식을 정상적으로 렌더링 하였습니다.
- 외부 라이브러리 사용 (better-react-mathjax)
- 문제 데이터의 경우 추후 HTML을 그대로 렌더링 하는 것으로 변경될 예정
- 수식 렌더링 성능 고려 필요
[better-react-mathjax GitHub](https://github.com/fast-reflexes/better-react-mathjax)
=> [FEATURE] 수식 데이터 전처리 로직 구현 (#81)

koco/src/pages/ProblemSolutionPage/components/ProblemDetailSection/index.tsx
[FEATURE] 예시 입력, 예시 출력이 여러개일 경우 구분 출력 (#88)
기존의 예시 입력/예시 출력 데이터는 두 줄씩 띄어져 있어 구분이 가능했으나 UI상으로는 하나의 블록으로 합쳐져 있었습니다.
이를 구분하여 출력하고,  예시 입,출력이 여러 세트일 경우 이를 구분하여 보여줍니다.
- closes #88 
- `processText` 함수 구현: 예시 입,출력 데이터에서 두 줄을 띄는 개행 문자가 있을 시, 이를 기반으로 나누어 배열로 리턴하는 함수입니다.
- 예시 입,출력 데이터를 하나의 div 안에 위치하여 첫 번째 예시-첫 번째 출력을 grid로 묶어 함께 보여지도록 수정하였습니다.
=> [FEATURE] 예시 입력, 예시 출력이 여러개일 경우 구분 출력 (#88)

koco/src/pages/ProblemSolutionPage/components/ProblemDetailSection/index.tsx, koco/src/utils/converter/processMathHtml.ts, koco/src/vite-env.d.ts
기존의 string 타입 데이터 렌더링 대신 html string을 렌더링하는 것으로 변경하였습니다.
- closes #91 
- 수식이 크롤링 과정에서 이중으로 처리되어, 이를 해결하기 위해 `processMathText` 함수를 구현하였습니다.
- 문제 해설 페이지의 글자 크기가 일관적이지 않았던 디자인을 수정하였습니다.
=> [ENHANCEMENT] 문제 영역 html 렌더링 및 수식 데이터 포맷 처리 함수 구현 (#91)

koco/index.html, koco/src/pages/ProblemSolutionPage/components/ProblemDetailSection/index.tsx, koco/src/styles/global.css, koco/src/utils/converter/processMathHtml.ts
- #111 
- 수식에서 사용되는 폰트를 preload하도록 변경
- MathJax 렌더링 완료 후 강제 리플로우
- position: static으로 수정
=> [CHORE] MathJax 폰트 preload, resize 이벤트 적용, css 수정 (#111)

koco/index.html, koco/src/styles/global.css
배포 환경에서 확인 결과 수식 렌더링 문제가 해결되었고, 해당 과정에서 불필요하게 추가 했던 css, preload를 제거하였습니다.
- #111 
- 배포 환경에서 확인 결과 수식이 정상적으로 렌더링되었습니다.
=> [CHORE] css 수정, 불필요한 폰트 preload제거 (#111)

koco/src/pages/ProblemSolutionPage/components/ProblemDetailSection/index.tsx, koco/src/styles/global.css
css가 로드된 후 MathJax가 렌더링 될 수 있도록 렌더링 순서를 제어합니다.
- #111
- 기존의 MathJax 라이브러리 렌더링을 위한 useEffect 코드에서 MathJax.typesetPromise()를 setTimeout에 맞춰 실행
=> [CHORE] MathJax 라이브러리 렌더링 순서 제어 (#111) 

src/features/post/api/getPostList.ts, src/features/post/hooks/useCreatePost.ts, src/pages/CreatePostPage/index.tsx, src/pages/PostsPage/index.tsx
카테고리 선택 후 게시글 등록 시 카테고리가 전송되지 않았던 이슈가 있어, 해결하였습니다.
- closes #164 
- 게시글 생성 api 함수인 `createPost`로 request data를 넘기는 과정에서 카테고리를 정상적으로 넘기지 않는 것을 확인해 수정하였습니다.
- 불필요한 콘솔 제거
=> [FIX] 게시글 등록시 카테고리 미전송 되는 이슈 해결 (#164)

src/pages/PostDetailPage/index.tsx, src/pages/PostsPage/index.tsx
하단 네비게이션 바에 의해 항목이 가려지는 이슈가 있어, padding-bottom으로 하단 네비게이션 바 높이 만큼 주었습니다.
- closes #160 
- 각 목록 태그에 `pb-20` 추가
=> [FIX] 하단 네비게이션 바에 항목(1개) 가려지는 현상 (#160)

src/features/post/api/getMyPosts.ts, src/features/post/api/getPostList.ts, src/features/post/components/PostForm.tsx, src/features/post/hooks/useGetPostList.ts, src/pages/EditPostPage/index.tsx
아래와 같은 이슈를 해결하였습니다.
- 수정 완료 후 게시글 페이지로 이동하지 않는 문제
- 게시글 상세 페이지에서 수정 페이지로 이동시 카테고리가 정상적으로 넘어가지 않아 값이 초기화 되어 있지 않은 문제
- closes #173 
- `useAlgorithmDropdown` 훅에서 영어->한글로 번역한 카테고리 초기화 하도록 수정
- 수정 완료 후 `post/${postId}` 로 이동하도록 수정
- 불필요한 콘솔 제거
=> [FIX] 게시글 수정 페이지 내 버그 해결 (#173)

src/features/alarm/api/getAlarmList.ts, src/features/alarm/utils/getAlarmMessage.ts, src/features/alarm/utils/getNotificationIcon.ts, src/pages/AlarmListPage/index.tsx
알람 메시지 UI 수정 및 유틸 함수 리팩토링
- close #183 
피그마 화면 설계서중 알림 메시지에 `postTitle`이 보여져야 하는 것을 확인하여, UI를 수정하였습니다.
이외 알람 메시지로 변환하는 유틸 함수 및 알람 아이콘을 얻는 유틸함수를 기능 내 utils 폴더에 배치하였습니다.
=> [FEATURE] 알람 메시지에 데이터 추가, 유틸 함수 분리 (#183)

src/features/post/components/PostForm.tsx
사용자 피드백에 따라, 게시판의 글자 수 제한을 확장합니다.
- closes #220 
- 사용자 피드백에 따라 글자 수 제한을 10,000자로 확장합니다.
=> [HOTFIX] 게시판 글자 수 제한 확장 (#220)

src/pages/ChattingPage/index.tsx
이전의 axios instance를 통해 401 에러 발생 시 토큰이 자동으로 리프레쉬 되도록 구현했지만
SSE 스트리밍에서는 axios를 사용할 수 없고, 따라서 fetch에서 사용할 리프레쉬 로직을 구현하였습니다.
- #224
- 함수를 책임에 맞게 분리했습니다. fetch 하다 401 에러 발생 시 -> `refreshToken` 함수 호출
- `refreshToken` 함수 구현
=> [FIX] fetch에서의 토큰 리프레쉬 로직 구현 (#224)

src/features/session/components/SessionItem.tsx, src/pages/SessionPage/index.tsx
대화 이력 항목을 클릭 시 전체 페이지가 리렌더링 되는 현상을 개선하였습니다.
- closes #230 
- `SessionItem` 컴포넌트 memo로 감싸 메모이제이션
- `SessionItem` 컴포넌트의 `onSelect` prop 때문에 리렌더링 되는 것을 방지하기 위해 useCallback으로 감싸 최적화
최적화 과정은 아래의 블로그에 기록해두었습니다🙇🏻‍♀️
https://hyemmimi.tistory.com/33
=> [ENHANCEMENT] 대화 이력 선택 - 리렌더링 최적화 (#230)

src/pages/ChattingPage/index.tsx
새로운 채팅 시작 시에는 마크다운 줄바꿈이 적용되었으나, 채팅 기록 데이터를 메시지로 렌더링할 때 마크다운 줄바꿈이 적용되지 않는 것이 발견되어 수정하였습니다.
- closes #236
- 이스케이프 문자를 제거하여 개행문자로 인식할 수 있도록 처리 :  `\\n` -> `\n` 으로 포맷
백엔드 측에 띄어쓰기 제거 요청 필요
=> [FIX] 채팅 기록 렌더링 시 마크다운 줄바꿈으로 포맷 (#236)

src/app/routes/Router.tsx
- 동적 import 사용하여 일부 페이지 지연로딩을 적용하였습니다. 
- **Slow 4G 기준 12.79s -> 7.08s 약 44.6%로 개선**
- closes #181 
주로 순차적으로 접근되는 페이지를 기준으로 적용하였습니다.
(ex. 로그인(1차) -> 메인페이지 (2차) -> 채팅방 생성 페이지 (3차) -> 채팅 페이지 (4차 접근))
- 채팅 페이지: 로그인 -> 챗봇 생성 페이지 → 성공 시 채팅페이지 / 챗봇 채팅방 생성을 위한 정보 입력 페이지를 거쳐야만 접근 가능한 페이지
- 게시글 상세, 작성페이지 : 메인 페이지 -> 하단의 커뮤니티 버튼 클릭 → 게시글 목록 페이지에서 접근 가능. 
- 게시글 수정페이지: 메인 페이지 -> 하단의 커뮤니티 -> 게시글 상세 -> (작성자일 경우) 수정 버튼 클릭 -> 수정 페이지
- 대화 이력 페이지 : 메인페이지 -> 더보기 페이지 -> 대화 이력 페이지 / 혹은 메인 페이지 -> 채팅방 생성 페이지 -> 채팅 페이지 -> 대화 이력 페이지
=> [ENHANCEMENT] 페이지 라우팅 단위 코드 스플리팅 적용 (#181)

src/features/post/components/LikeBoxWithActions.tsx
좋아요 상태를 낙관적 업데이트(로컬에서 미리 상태 변경)합니다.
- closes #249 
- try, catch 문 내에서 await를 사용하고 있지 않았던 에러 코드 수정
- 서버 응답 전 로컬에서 미리 업데이트 하도록 수정 (낙관적 업데이트)
- 서버 응답 실패 시 롤백 로직 추가
=> [CHORE] 좋아요 낙관적 업데이트 및 서버 응답 실패 시 롤백 로직 구현 (#249)
