koco/src/hooks/queries/useUserQueries.ts, koco/src/pages/MainPage/index.tsx
[CHORE] 메인페이지 - 사용자 대시보드 api 연결 (#21)
메인페이지의 대시보드 api 연결을 완료하였습니다.
- closes #21 #22 #20 
- 더미데이터 삭제
=> [CHORE] 메인페이지 - 사용자 대시보드 api 연결 (#21)

koco/src/App.tsx, koco/src/apis/axios/index.ts, koco/src/components/ui/Spinner/index.tsx, koco/src/context/AuthContext.tsx, koco/src/hooks/mutations/useAuthMutations.ts, koco/src/pages/KakaoCallbackPage/index.tsx, koco/src/pages/Login/index.tsx, koco/src/routes/ProtectedRoute/index.tsx, koco/src/routes/RootRoutes.tsx
[FEATURE] 자동 로그인 기능 구현 (#30)
`context API`, `로컬 스토리지` 기반 자동 로그인 기능을 구현하였습니다.
- closes #30 
- 로그인, 로그아웃 뮤테이션 성공 시 로그인, 로그아웃 여부를 확인할 수 있는 플래그를 로컬스토리지에 추가 및 삭제하여 자동 로그인을 구현하였습니다.
- 로그인 완료된 사용자만 접근할 수 있도록 라우팅을 수정하였습니다.
=> [FEATURE] 자동 로그인 기능 구현 (#30)

koco/src/pages/Login/components/LoginCard/index.tsx
[FIX] 로그아웃 후 별도의 로그인 과정 없이 로그인 되는 현상 수정 (#36)
Kakao oauth 링크를 수정하였습니다.
- closes #36 
- prompt=login을 URL에 포함시켜서,  사용자가 이미 로그인되어 있어도 강제로 로그인 화면을 표시하도록 설정
=> [FIX] 로그아웃 후 별도의 로그인 과정 없이 로그인 되는 현상 수정 (#36)

koco/src/apis/axios/index.ts, koco/src/pages/ProblemSolutionPage/components/ProblemDetailSection/index.tsx, koco/src/pages/ProblemSolutionPage/components/ProblemSolutionSection/index.tsx, koco/src/pages/ProblemSolutionPage/index.tsx
[CHORE] 문제 해설 페이지 - 코드 영역 개행 문자 적용, 누락된 데이터 반영, UI 디자인 수정 (#40)
문제 해설 페이지의 코드 부분에서 \n이 적용되지 않는 문제를 해결하였습니다.
그 외 UI 및 디자인이 수정되었습니다.
- #40 
- 문제 앞으로 가기, 뒤로 가기 UI를 제거하였습니다.
- UI 디자인을 수정하였습니다.
- 코드 영역 복사하기 버튼 및 이벤트를 추가하였습니다.
-[X] 누락된 데이터 반영
-[X] UI 수정
-[X] 코드 개행 문자 적용
-[X] 복사하기 기능 추가
=> [CHORE] 문제 해설 페이지 - 코드 영역 개행 문자 적용, 누락된 데이터 반영, UI 디자인 수정 (#40)

koco/src/pages/ProblemSolutionPage/components/ProblemSolutionSection/index.tsx, koco/src/pages/SurveyPage/index.tsx
[BUG] 문제 해설 페이지 - 문자열 개행 문자 적용 (#59)
개행문자 \n을 적용하도록 수정하였습니다.
- closes #59 
풀이 부분 string 데이터에서 개행 문자가 적용되지 않아 whitespace-pre-line 클래스를 추가하였습니다.
=> [BUG] 문자열 개행 문자 적용 (#59)

koco/src/pages/ProblemListPage/index.tsx, koco/src/pages/SurveyPage/index.tsx
[CHORE] 문제 리스트 조회 페이지 - 하단바 추가 및 불필요한 조건부 렌더링 제거 (#60)
하단바를 추가하였으며, 불필요한 조건부 렌더링을 제거하였습니다. (리팩토링)
- closes #60 
- problemListData가 없을 경우 보여주려고 했던 조건부 렌더링을 제거하였습니다 (이미 중복된 UI 존재)
=> [CHORE] 문제 리스트 조회 페이지 - 하단바 추가 및 불필요한 조건부 렌더링 제거 (#60)

koco/src/pages/MainPage/index.tsx, koco/src/pages/ProblemSolutionPage/components/ProblemSolutionSection/index.tsx
[FEATURE] 문제 해설 페이지 - problemSolving 데이터 포맷 함수 구현 (#71)
problemSolving 데이터를 포맷합니다.
closes #71 
어떤 데이터는 1. ~했다.\n2.~했다. 이런식으로 온다면 어떤 데이터는 1. ~했다. 2.~했다. 이런 식으로 와서 UI 상 일관성이 깨지는 일이 발생하여, 포맷 함수를 구현하였다.
=> [FEATURE] 문제 해설 페이지 - problemSolving 데이터 포맷 함수 구현 (#71)

koco/src/apis/problemApi.ts, koco/src/pages/ProblemSolutionPage/components/ProblemDetailSection/index.tsx
[FEATURE] 백준 문제 바로가기 UI 구현 (#70)
문제 해설 페이지의 '백준 문제 바로가기' 버튼을 클릭하면 링크로 이동하도록 구현합니다.
- closes #70 
추가 기능으로 구현되었습니다.
=> [FEATURE] 문제 해설 페이지 - 백준 문제 바로가기 UI 구현 (#70)

koco/src/pages/MainPage/components/ProblemItem/index.tsx, koco/src/pages/MainPage/index.tsx
- 작업한 기능이나 수정 사항에 대한 간략한 설명
- #이슈번호
- 여러 개 연관 시 모두 명시
- 구체적으로 어떤 코드를 수정/추가/삭제했는지
- 이렇게 변경한 이유 (배경)
- ex) "메서드 네이밍을 더 직관적으로 만들고 싶은데 조언 부탁드립니다."
=> [FEATURE] 메인 페이지 ui 수정

koco/src/apis/axios/index.ts, koco/src/apis/problemApi.ts, koco/src/apis/userApi.ts, koco/src/hooks/mutations/useAuthMutations.ts, koco/src/pages/ProblemSolutionPage/components/ProblemSolutionSection/index.tsx, koco/src/pages/SurveyPage/index.tsx
[CHORE] 콘솔 제거 (#80)
불필요한 콘솔로그를 삭제하였습니다.
closes #80
=> [CHORE] 콘솔 제거 (#80)

koco/src/apis/axios/index.ts, koco/src/context/AuthContext.tsx, koco/src/pages/FirstLoginPage/index.tsx, koco/src/routes/ProtectedRoute/index.tsx, koco/src/routes/RootRoutes.tsx
[ENHANCEMENT] 라우팅 로직 변경 (#67)
라우팅 로직을 수정하였습니다.
- #67
- qa 모드 제거에 따라 환경 변수에 따른 base url 렌더링을 삭제하였습니다.
=> [ENHANCEMENT] 라우팅 로직 변경 (#67)

src/pages/MainPage/index.tsx
- 춘식이 게임 바로가기 URL을 변경하였습니다.
- close #146
- 잘못된 URL 경로를 수정하였습니다.
=> [FIX] 라우팅 수정 (#146)

src/features/post/api/createPost.ts, src/features/post/api/getPostList.ts, src/features/post/components/PostItem.tsx, src/features/post/hooks/useGetPostList.ts, src/pages/CreatePostPage/index.tsx, src/pages/PostsPage/index.tsx
게시글 목록을 조회하는 api를 연결합니다.
- close #138 
- 목업 데이터 삭제
=> [FEATURE] 게시글 목록 조회 및 검색 기능 api 연결, 구현  (#138)

src/app/routes/Router.tsx, src/features/post/api/editPost.ts, src/features/post/components/PostForm.tsx, src/features/post/components/PostMeta.tsx, src/features/post/hooks/useCreatePost.ts, src/features/post/hooks/useEditPost.ts, src/pages/CreatePostPage/index.tsx, src/pages/EditPostPage/index.tsx, src/pages/PostDetailPage/index.tsx, src/shared/hooks/useAlgorithmDropdown.ts, src/shared/hooks/useInput.ts
게시글 편집 API를 연결하고 게시글 등록 페이지 UI를 재사용하기 위해 컴포넌트를 분리합니다.
- close #129
- 구체적으로 어떤 코드를 수정/추가/삭제했는지
- 이렇게 변경한 이유 (배경)
=> [FEATURE] 게시글 편집 기능 구현

src/constants/queryKeys.ts, src/features/alarm/api/confirmAlarm.ts, src/features/alarm/api/deleteAlarm.ts, src/features/alarm/api/getAlarmList.ts, src/features/alarm/hooks/useConfirmAlarm.ts, src/features/alarm/hooks/useDeleteAlarm.ts, src/features/alarm/hooks/useGetAlarmList.ts, src/features/post/api/getMyPosts.ts, src/features/post/api/getPostList.ts, src/features/post/hooks/useGetMyPosts.ts, src/features/post/hooks/useGetPostList.ts, src/pages/CreatePostPage/index.tsx, src/pages/PostsPage/index.tsx
API 호출 함수와 훅을 구현합니다.
- 알람 삭제/조회/확인
- 내 게시물 조회
- #153 
인기 게시물 조회 API가 아직 미완료이므로 추후 반영할 예정입니다.
=> [CHORE] API 호출 함수, 훅 구현 (#153)

src/app/routes/Router.tsx, src/pages/AlarmListPage/index.tsx, src/pages/MainPage/index.tsx, src/shared/layout/Header.tsx, tailwind.config.ts
메인 페이지 내 알람 아이콘을 구현하고, 클릭하면 알람을 조회할 수 있는 페이지로 이동하도록 구현합니다.
- close #135
=> [FEATURE] 알람 리스트 페이지 UI 구현 (#135)

src/features/comment/api/editComment.ts, src/features/comment/components/commentItem.tsx, src/features/comment/hooks/useEditComment.ts, src/pages/PostDetailPage/index.tsx
댓글 수정 관련 API 함수 및 훅 구현, UI 구현, 연결
- close #179 
- 수정 버튼 클릭하면 수정 모드(input) 전환
수정, 삭제 버튼 추후 디자인 변경 가능성 있음
=> [FEATURE] 댓글 수정 기능 구현 (#179)

package-lock.json, package.json, src/app/App.tsx, src/pages/MainPage/index.tsx, src/shared/hooks/useNotification.ts, src/shared/layout/Header.tsx, src/shared/ui/Toast/ToastItem.tsx, src/shared/ui/Toast/index.tsx, src/stores/useAlarmStore.ts
SSE 구독 및 토스트 메시지 전송
- #171 
- `Zustand` 도입 -> 알람 전역 상태 관리
- 메인 페이지 내 알람 발생 시 토스트 메시지
=> [FEATURE] SSE 실시간 알림 연결 및 토스트 메시지 구현 (#171)

src/features/comment/components/commentInputBox.tsx, src/features/post/components/PostMeta.tsx, src/pages/PostDetailPage/index.tsx
- 상세 페이지의 문제 번호 누락된 것 수정
- 댓글 엔터 입력 기능 추가
=> [HOTFIX] UI QA 적용

src/pages/ChattingPage/index.tsx
챗봇 채팅 페이지 코드 리팩토링
- #224 
불필요하게 text/event-stream 응답 형식을 검사했던 코드를 없애고 fetch에서의 content-type 및 accept 타입을 지정하였습니다.
버튼이 items-end 되어 있던 스타일을 center로 수정하였습니다.
=> [CHORE] 챗봇 채팅 페이지 fetch accept, content-type 지정 및 스타일 수정, 리팩토링 (#224)

src/constants/queryKeys.ts, src/features/problemSet/api/getRecommendedProblem.ts, src/features/problemSet/hooks/useGetRecommededProblem.ts, src/features/session/hooks/useGetSessionHistory.ts, src/pages/ChattingPage/index.tsx, src/pages/MainPage/index.tsx, src/pages/SessionPage/index.tsx
AI로부터 유저 수준에 맞는 추천 문제를 조회하는 기능을 메인페이지에 추가하였으며,
기존의 챗봇 데이터를 마크다운 형식에 맞게 줄바꿈 포맷을 추가하였습니다.
- closes #234 
- 마크다운 `\\n` 을 마크다운 줄바꿈에 맞게 `  \n`으로 replace
- ex) "메서드 네이밍을 더 직관적으로 만들고 싶은데 조언 부탁드립니다."
=> [FEATURE] AI 추천 문제 조회 기능 구현 및 챗봇 마크다운 줄바꿈 추가 (#234)

src/shared/hooks/useDebounce.ts, src/shared/ui/AlgorithmDropdown/index.tsx
- 유저가 알고리즘 유형을 선택할 수 있는 드롭다운에 검색 기능을 추가하였습니다.
- closes #245 
- `AlgorithmDropdown.tsx` 파일 내 검색 ui, 로직 추가
- `useDebounce` 훅 구현하여 일정 딜레이 시간 동안은 검색 되지 않도록 최적화
=> [FEATURE] Debounce 적용한 알고리즘 유형 검색 기능 구현 (#245)

src/pages/PostsPage/index.tsx
기존의 엔터 혹은 아이콘 클릭 시 검색이 되는 구조에서 유저가 입력 시 바로 검색 되도록 UX를 개선하였습니다. 
-close #252 
- `PostsPage` 내 실시간 검색 모드를 관리하는 boolean 상태 변수 추가
- 기존의 검색 input의 onChange를 래핑하여 실시간 검색 시 `isRealTimeSearch` 상태 변수를 바꾸도록 변경
- `isRealTimeSearch` 값이 true인 경우 debounce된 값으로 검색, false인 경우 `appliedKeyword` 값으로 검색 (세션 스토리지에 저장된 검색 값이 동기화 된 상태 값)
API 호출: 18번
API 호출: 2번
=> API 호출 횟수 총 **88%** 단축
=> [FEATURE] 게시글 목록 실시간 검색 및 debounce 구현 (#252)
